### Get top 10 games
GET http://localhost:4004/odata/v4/game/Game?$top=10

### Get All Students
GET http://localhost:4004/odata/v4/game/Student

### Get a student with their favorite games
GET http://localhost:4004/odata/v4/game/Student(fe56efd2-85a2-4928-8127-af094a6d4653)?$expand=to_favos($expand=to_game)

### Create a new student
POST http://localhost:4004/odata/v4/game/Student
Content-Type: application/json

{
  "First_name": "John",
  "Last_name": "Doe"
}

### Create a new favorite game for a student
POST http://localhost:4004/odata/v4/game/FavoriteGame
Content-Type: application/json

{
  "Game_ID": 1,
  "Student_ID": "4750d5e1-d661-42cf-a6fb-5d5f14da9d02"
}

### Update a student with their favorite games
PATCH http://localhost:4004/odata/v4/game/Student(fe56efd2-85a2-4928-8127-af094a6d4653)
Content-Type: application/json

{
  "First_name": "Tom2",
  "Last_name": "Antjon2",
  "to_favos": [
    {
      "Game_ID": 1,
      "Student_ID": "fe56efd2-85a2-4928-8127-af094a6d4653"
    },
    {
      "Game_ID": 2,
      "Student_ID": "fe56efd2-85a2-4928-8127-af094a6d4653"
    }
  ]
}

### Try to delete a game
DELETE http://localhost:4004/odata/v4/game/Game(1)
